import type { Metadata } from 'next'
import { Bricolage_Grotesque } from 'next/font/google'
import '@/app/globals.css';
import Header from '@/components/Layout/Header2'
import Footer from './components/Footer'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import SessionProviderComp from '@/components/nextauth/SessionProvider'
import Header2 from '@/components/Layout/Header1'
import { Toaster } from 'react-hot-toast';

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Property Plus Africa - A Real Estate Framer Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode
  session: any
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#FF8C00" />
        {/* <SessionProviderComp session={session}> */}
          <ThemeProvider
            attribute='class'
            enableSystem={true}
            defaultTheme='light'>
            {/* <Header />
            <Header2 /> */}
            <Toaster position="top-right" />
            {children}
            {/* <Footer /> */}
          </ThemeProvider>
        {/* </SessionProviderComp> */}
      </body>
    </html>
  )
}
